#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: userservice
#          uri: lb://USERSERVER
#          predicates:
#            - Path=/api/v1/user/**
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#eureka:
#  client:
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    prefer-ip-address: true